### ISSUE TITLE
[KED-2536] `kedro ipython` and `kedro jupyter` are broken if PYTHONPATH is already set

### ISSUE THREAD

**Issue by sansagara** [quantumblacklabs/kedro#727]
## Description
Edit: After some discussion/investigation, the issue was found: _add_src_to_path does not work correctly when there's a _PYTHONPATH_ set.

Old description:
I realize you are very aware of the issue at this point: TemplatedConfigLoader is failing on Kedro 17.1 and 17.2. I think the fix is in the works [here](https://github.com/quantumblacklabs/kedro/commit/c705a15c5706595043a6156a9233f894c75cd7b5).
Just wondering if you plan to have this released soon, as we have a different technical difficulty on 17.0 that makes downgrading not the ideal solution.

Thanks!

**Comment by datajoely** [comment]
Could you post your stack trace?

**Comment by sansagara** [comment]
Sorry, I only got a screenshot of the last part:
![image](https://user-images.githubusercontent.com/1382235/111622792-e25ff000-87e9-11eb-8c78-7d846ce65c02.png)

But, it's very similar to this one:
https://discourse.kedro.community/t/expected-an-instance-of-configloader-got-nonetype-instead/401

**Comment by AntonyMilneQB** [comment]
Hello @sansagara. The fix c705a15c5706595043a6156a9233f894c75cd7b5 is actually for something else (a very minor issue which only matters if you have an empty globals.yml file when using `TemplatedConfigLoader`.

The "Expected an instance of `ConfigLoader`, got `NoneType` instead" error should have been resolved with upgrading to kedro 0.17.2. The problem (in 0.17.1) was that the real error message that caused this (which could be, for example, an `ImportError` due to misnaming a file in an import) was hidden and it threw the `KedroContextError` instead. This should, however, no longer be the case, and the real error message should be raised.

So I would double check that you're running kedro 0.17.2 to make sure that the error message you're receiving is not hiding the actual problem here. If you are on 0.17.2, please could you post what's in your settings.py, hooks.py and pipeline_registry.py files?

**Comment by istratig** [comment]
Hello

I am joining the same discussion - as we tried to migrate from 0.17.0 to 0.17.1 because of some old dependencies (pyarrow>=0.12.0, <3.0.0) and we tried first 17.1 - there we had the issue mentioned already with the masked exception and migrating to 0.17.2 gives the other error of TemplatedConfigLoader mentioned above. In this context this becomes a serious issue as  we cannot migrate - see below the original context.

Thanks.
---
ERROR: Cannot install kedro[pandas]==0.17.0 and pyarrow>=3.0.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested pyarrow>=3.0.0
    kedro[pandas] 0.17.0 depends on pyarrow<1.0.0 and >=0.12.0; extra == "pandas"
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by limdauto** [comment]
@sansagara Could you paste the whole stack trace please? Usually the problem is higher up in the trace, since the final exception masks the original problem. 

@istratig could you paste the whole stack trace when you try to migrate to 0.17.1 and 0.17.2 please?

**Comment by sansagara** [comment]
Greetings @AntonyMilneQB. Thanks for the quick reply!!.
I am indeed in 17.2:

```
(/root/user_files/env/xpvu-kedro-starter) [root@674e22255d99 xpvu-kedro-starter]# kedro -V
kedro, version 0.17.2
```

This is the full stack trace, coming from an python session. But I noticed same issue happens when trying to run a Jupiter notebook:

```
In [2]: %reload_kedro /root/user_files/projects/my-new-project
2021-03-18 13:04:43,548 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
---------------------------------------------------------------------------
KedroContextError                         Traceback (most recent call last)
<ipython-input-2-95e8ad5f37db> in <module>
----> 1 get_ipython().run_line_magic('reload_kedro', '/root/user_files/projects/my-new-project')

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/extras/extensions/ipython.py in load_kedro_objects(path, line)
     85     _remove_cached_modules(metadata.package_name)
     86 
---> 87     session = KedroSession.create(metadata.package_name, path)
     88     _activate_session(session)
     89     logging.debug("Loading the context from %s", str(path))
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/session/session.py in create(cls, package_name, project_path, save_on_close, env, extra_params)
    202 
    203         # we need a ConfigLoader registered in order to be able to set up logging
--> 204         session._setup_logging()
    205         return session
    206 
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/session/session.py in _setup_logging(self)
    220     def _setup_logging(self) -> None:
    221         """Register logging specified in logging directory."""
--> 222         conf_logging = self._get_logging_config()
    223         logging.config.dictConfig(conf_logging)
    224 
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/session/session.py in _get_logging_config(self)
    208         context = self.load_context()
    209 
--> 210         conf_logging = context.config_loader.get(
    211             "logging*", "logging*/**", "**/logging*"
    212         )
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/context/context.py in config_loader(self)
    454 
    455         """
--> 456         return self._get_config_loader()
    457 
    458     def _get_feed_dict(self) -> Dict[str, Any]:
 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/context/context.py in _get_config_loader(self)
    438         if not isinstance(config_loader, ConfigLoader):
    439             raise KedroContextError(
--> 440                 f"Expected an instance of `ConfigLoader`, "
    441                 f"got `{type(config_loader).__name__}` instead."
    442             )

KedroContextError: Expected an instance of `ConfigLoader`, got `NoneType` instead.
```

**Comment by limdauto** [comment]
@sansagara hi ya, in the release note, we mentioned that the `kedro ipython` and `kedro jupyter` workflow will need updating with 0.17.2: https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#breaking-changes-to-the-api

Specifically, you need to add a couple of lines of code to `<your_project>/.ipython/profile_default/startup/00-kedro-init.py` before the `KedroSession` is created. Alternatively, you can replace the existing `00-kedro-init.py` with this file: https://github.com/quantumblacklabs/kedro/blob/0.17.2/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.ipython/profile_default/startup/00-kedro-init.py

**Comment by sansagara** [comment]
Hi @limdauto .
Yes, when I do this the error did change. Now I get:

```
(/root/user_files/env/xpvu-kedro-starter) [root@674e22255d99 my-new-project]# kedro ipython
-------------------------------------------------------------------------------
Starting a Kedro session with the following variables in scope
startup_error, context
Use the line magic %reload_kedro to refresh them
or to see the error message if they are undefined
-------------------------------------------------------------------------------
ipython
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.0 -- An enhanced Interactive Python. Type '?' for help.
2021-03-18 13:17:24,195 - root - ERROR - Kedro's ipython session startup script failed:
No module named 'my_new_project'
Traceback (most recent call last):
  File "/root/user_files/projects/my-new-project/.ipython/profile_default/startup/00-kedro-init.py", line 55, in reload_kedro
    configure_project(metadata.package_name)  # to add
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py", line 162, in configure_project
    _validate_module(settings_module)
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py", line 154, in _validate_module
    importlib.import_module(settings_module)
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_new_project'
[TerminalIPythonApp] WARNING | Unknown error in handling startup files:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/IPython/core/shellapp.py in _exec_file(self, fname, shell_futures)
    338                                                  self.shell.user_ns,
    339                                                  shell_futures=shell_futures,
--> 340                                                  raise_exceptions=True)
    341         finally:
    342             sys.argv = save_argv

 

~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/IPython/core/interactiveshell.py in safe_execfile(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)
   2710                 py3compat.execfile(
   2711                     fname, glob, loc,
-> 2712                     self.compile if shell_futures else None)
   2713             except SystemExit as status:
   2714                 # If the call was made with 0 or None exit status (sys.exit(0)


~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/IPython/utils/py3compat.py in execfile(fname, glob, loc, compiler)
    186     with open(fname, 'rb') as f:
    187         compiler = compiler or compile
--> 188         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    189 
    190 # Refactor print statements in doctests.


~/user_files/projects/my-new-project/.ipython/profile_default/startup/00-kedro-init.py in <module>
     74 
     75 
---> 76 reload_kedro(project_path)

 
<decorator-gen-109> in reload_kedro(path, line)

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    218     # but it's overkill for just that one bit of state.
    219     def magic_deco(arg):
--> 220         call = lambda f, *a, **k: f(*a, **k)
    221 
    222         # Find get_ipython() in the caller's namespace


~/user_files/projects/my-new-project/.ipython/profile_default/startup/00-kedro-init.py in reload_kedro(path, line)
     71             "Kedro's ipython session startup script failed:\n%s", str(err)
     72         )
---> 73         raise err
     74 
     75 


~/user_files/projects/my-new-project/.ipython/profile_default/startup/00-kedro-init.py in reload_kedro(path, line)
     53             del sys.modules[module]
     54 
---> 55         configure_project(metadata.package_name)  # to add
     56         session = KedroSession.create(metadata.package_name, path)
     57         _activate_session(session, force=True)


~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py in configure_project(package_name)
    160     """
    161     settings_module = f"{package_name}.settings"
--> 162     _validate_module(settings_module)
    163     settings.configure(settings_module)
    164 


~/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py in _validate_module(settings_module)
    152     correct so that any import errors are surfaced early.
    153     """
--> 154     importlib.import_module(settings_module)
    155 
    156 


~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

 
~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)


~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)


~/user_files/env/xpvu-kedro-starter/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'my_new_project'
```

**Comment by limdauto** [comment]
@sansagara no, `kedro ipython` should work because the Kedro CLI automatically add the source directory to the Python path for you. Could you show me your project tree? What's the package name under `src/`? It looks like it's something else other than `my_new_project`

**Comment by sansagara** [comment]
It is. :(

```
(/root/user_files/env/xpvu-kedro-starter) [root@674e22255d99 my-new-project]# pwd
/root/user_files/projects/my-new-project

(/root/user_files/env/xpvu-kedro-starter) [root@674e22255d99 my-new-project]# tree -d .
.
- conf
|- - base
|- |- - catalogs
|- |- - parameters
|- |-     - model_tree
|- |-     - sales_prediction
|- |-     - segmentation
|- - img
|- - local
- data
|- - 01_raw
|- - 02_intermediate
|- - 03_primary
|- - 04_feature
|- - 05_model_input
|- - 06_models
|- - 07_model_output
|- - 08_reporting
|- - sample_data
- docs
|- - source
- logs
|- - journals
- notebooks
- src
|- - my_new_project
|- |- - pipelines
|- |- |- - data_engineering
|- |- |- |- - nodes
|- |- |- |- |- - common
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- - __pycache__
|- |- |- |- |- - u02_intermediate
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- - u03_primary
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- - u04_features
|- |- |- |- |- |- - events
|- |- |- |- |- |- |- - __pycache__
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- - u05_master
|- |- |- |- |-     - __pycache__
|- |- |- |- - __pycache__
|- |- |- - data_extraction
|- |- |- |- - __pycache__
|- |- |- - data_science
|- |- |- |- - nodes
|- |- |- |- |- - common
|- |- |- |- |- |- - feature_selection
|- |- |- |- |- |- |- - __pycache__
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- - __pycache__
|- |- |- |- |- - u01_ds_mst
|- |- |- |- |- |- - preprocessing
|- |- |- |- |- |- |- - __pycache__
|- |- |- |- |- |- - __pycache__
|- |- |- |- |- |- - sales_allocation
|- |- |- |- |- |- |- - __pycache__
|- |- |- |- |- |- - target_universe
|- |- |- |- |- |-     - __pycache__
|- |- |- |- |- - u02_models
|- |- |- |- |-     - model_trees
|- |- |- |- |-     - sales_prediction
|- |- |- |- |-     - segmentation
|- |- |- |- - __pycache__
|- |- |- - __pycache__
|- |- - __pycache__
|- - tests
|-     - pipelines
- utils
```

**Comment by limdauto** [comment]
@sansagara crazy idea but can you delete all `__pycache__` and try again?

**Comment by roumail** [comment]
Hi, @sansagara's teammate here. Below should be enough to reproduce the error on 17.2, please let me know if there's anything else I can provide. We're pretty blocked with the 0.17.x version in general, each version released so far presents a different challenge

```
sh-4.2# kedro --v
sh-4.2# kedro --version
kedro, version 0.17.2
sh-4.2# kedro new --starter=pandas-iris

project name:
=============
please enter a human readable name for your new project.
Spaces and punctuation are allowed.
[new kedro project]: test_jupyter

repository name:
================
please enter a directory name for your new project repository.
Alphanumeric characters, hyphens and underscores are allowed.
Lowercase is recommended.
[test_jupyter]:

python package name:
====================
please enter a valid python package name for your project package.
Alphanumeric characters and underscores are allowed.
Lowercase is recommended. Package name must start with a letter
or underscore.
[test_jupyter]:

change directory to the project generated in /root/user_files/testing/test_jupyter

a best-practice setup includes initialising git and creating a virtual environment before running ``kedro install`` to install project-specific dependencies. Refer to the kedro documentation: https: //kedro. Readthedocs. Io/[0m
sh-4.2# cd test_jupyter/
sh-4.2# ls
conf data docs logs	notebooks pyproject. Toml readme. Md setup. Cfg src
sh-4.2# kedro ipython
```

**Comment by roumail** [comment]
Let me also add a test notebook to see if kedro jupyter notebook works. I have a simple notebook containing the following cells that I launch using ` kedro jupyter notebook --allow-root --ip='0.0.0.0' --port=8888` from inside the project directory:
![image](https://user-images.githubusercontent.com/32498483/111648111-59ee4900-8803-11eb-9f0c-f851fa10d04d.png)


I was expecting context and catalog to already be loaded when I launch a notebook in this manner. There's no error per say when I execute the command:

![image](https://user-images.githubusercontent.com/32498483/111648336-8904ba80-8803-11eb-966b-61afbb8d42d9.png)

**Comment by roumail** [comment]
Next thing I tried is to load without a notebook without the kedro prefix using `jupyter notebook --allow-root --ip='0.0.0.0' --port=8888` and tried to load the context (to eventually get access to the catalog) and got all types of errors. I attach the notebook as a zip file but summary of things I tested:  
1. Do it in documented manner (https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#breaking-changes-to-the-api)  
2. change notebook working directory to project root and try loading the session - this has often been the workaround we've used in the past
3. Add src to python path using `_add_src_to_path(metadata.source_dir, PROJECT_ROOT)` prior to loading session. This was the fix for kedro ipython in 0.17.0 but no longer seems to do the job
Please let me know if there's any more information needed. I can do a pip freeze or something but basically I created a conda environment using `conda create -n kedro python=3.7 kedro==0.17.2 jupyter`
[test_kedro_jupyter_nb.zip](https://github.com/quantumblacklabs/kedro/files/6165162/test_kedro_jupyter_nb.zip)

**Comment by roumail** [comment]
PS: kedro run works -- so this is an issue for ipython and notebook specifically

**Comment by limdauto** [comment]
@roumail thank you so much. Let me try to reproduce with your steps.

**Comment by roumail** [comment]
Once you're able to reproduce the errors, we'd also love some feedback on how to proceed since we're a bit blocked. We can ignore the kedro ipython and jupyter catalog functionality and simply try accessing our datasets using the standard s3 methods? I only ask this because there's probably still some time until we 0.18 is released?

**Comment by limdauto** [comment]
@roumail sorry I'm struggling to reproduce. I'm trying a couple of things. In the mean time, can you try the following

## Option 1: Use Kedro [IPython extension](https://kedro.readthedocs.io/en/0.17.2/11_tools_integration/02_ipython.html#ipython-extension)

```python
In [1]: %load_ext kedro.extras.extensions.ipython
In [2]: %reload_kedro <path_to_project_root>
```

That has the same effect as `kedro ipython` and `kedro jupyter notebook`

## Option 2: Manually activate a session

* Launch `ipython` or `jupyter notebook` without going through `kedro`
* Paste the following at the top of your notebook

```python
from pathlib import Path
from kedro.framework.session import KedroSession
from kedro.framework.startup import _get_project_metadata
from kedro.framework.cli.utils import _add_src_to_path
from kedro.framework.project import configure_project
from kedro.framework.session.session import _activate_session
current_dir = Path.cwd()  # this points to 'notebooks/' folder.
project_path = current_dir.parent  # point back to the root of the project. OR CHANGE THIS TO THE DESIRED PATH
metadata = _get_project_metadata(project_path)
_add_src_to_path(metadata.source_dir, project_path)
configure_project(metadata.package_name)
session = KedroSession.create(metadata.package_name, project_path)
_activate_session(session)
context = session.load_context()
```

The second approach would absolutely work.

But ideally you shouldn't need to do any of this at all :) In the mean time, let me continue digging.

**Comment by roumail** [comment]
Hi, thanks for the quick feedback. Let me try these steps out and confirm that they work. In the meantime, I'll also investigate why you're unable to reproduce my error.. I find that strange..

**Comment by sansagara** [comment]
I definitely tried option1 myself @roumail. Same thing for me.

**Comment by limdauto** [comment]
@roumail Yea please see below my attempt to follow your steps to recreate:

![output2](https://user-images.githubusercontent.com/2032984/111667502-abe79c80-880c-11eb-88de-44fe5fb9ce43.gif)

**Comment by roumail** [comment]
Okay I can verify that 
Option I
1) doesn't work on the reproducible example nor our actual codebase. Am I calling %reload_kedro correctly like this? `%reload_kedro "/root/user_files/testing/test_jupyter"`. This gives me the error -> 
![image](https://user-images.githubusercontent.com/32498483/111668921-90818f00-8816-11eb-911b-f412a3018674.png)

Option II 
1) works on the reproducible example but not on our actual codebase. There I get the error: 

![image](https://user-images.githubusercontent.com/32498483/111669190-d2aad080-8816-11eb-8668-b41501b8a8c7.png)

This error seems to be related to somewhere in our codebase where we load the configuration. It complains that conf/base/parameters doesn't exist when it does.. I will need to investigate this

**Comment by roumail** [comment]
PS @limdauto how did you make that screen capture? cool way to share reproducible examples :)

**Comment by roumail** [comment]
Okay I just tried to reproduce the steps from your screen grab with a new conda environment (python 3.7) and after doing kedro new, kedro install and kedro ipython I get this new error:

![image](https://user-images.githubusercontent.com/32498483/111670948-b314a780-8818-11eb-877c-a78677923fca.png)

**Comment by roumail** [comment]
Complete reproduction steps
1. conda create -n kedro kedro==0.17.2
2. conda activate kedro
3. kedro new (config name --> test_jupyter)
4. kedro install
5. cd test_jupyter
6. kedro ipython

**Comment by limdauto** [comment]
@roumail I still works for me on a fresh install. I notice that you have step 4 and 5 out of order in your steps. You should cd into the project first before running `kedro install`.

Regarding the error on your actual code base after you follow option 2, I noticed that you are using relative path when instantiating the config loader manually. Can you check whether the paths exist _relative to_ your notebooks?

**Comment by sansagara** [comment]
We are now thinking this is somehow related to or setup.
We've tried this on my personal Mac, and it works...

I wonder it this has to be with our work dockerized development environment?
In any case, thanks for sticking with us!!

**Comment by roumail** [comment]
Updated reproduction steps:
```
1. conda create -n kedro kedro==0.17.2 python=3.8
2. conda activate kedro
3. kedro new (config name --> test_jupyter)
4. cd test_jupyter
5. kedro install
6. kedro ipython
```
![image](https://user-images.githubusercontent.com/32498483/111676271-4dc3b500-881e-11eb-8193-014861216835.png)

It's again complaining that my created project is not found (test_jupyter). Normally in a jupyter notebook session I'd use the private function _add_src_to_path to get around this issue...

Regarding your comment about manually instantiating the config load, I can't update the paths to be relative to the notebooks because I mainly use it for executing pipelines. I can make sure that when loading the session in the notebook, I set my project root as working directory...

**Comment by limdauto** [comment]
@roumail I noticed something very strange: The normal Python stacktrace points to `/root/user_files/testing/test_jupyter` as your project root but your IPython is pointing at `~/user_files/`. It looks like the project python process is running inside a container but the ipython process is running , erm, outside? I'm not entirely sure, but it could explain the error. One process, i.e. the `kedro ipython` process, has been instantiated correctly but the IPython one isn't because it's separate somehow.

> I can make sure that when loading the session in the notebook, I set my project root as working directory

Yea can you try that just in case?

**Comment by roumail** [comment]
Very interesting. It makes sense now that kedro uses a session framework, it’s creating challenges for our containerized workflow. We have been using this  setup for a couple years and have been using kedro ipython and liading context in notebook etc. 

The other point to consider is that kedro ipython was working with 0.17.0 but breaking with 17.2. 

I have a few ideas for things to try out. Let me try the steps above with kedro 17.0 as well as your other suggestions. I’ll get back to you tomorrow

**Comment by limdauto** [comment]
Thank you for following up. Let me summarise the discussion here from a Kedro point of view:

1. To go from `kedro==0.17.0` to `kedro==0.17.2`, you will need to update the `00-kedro-init.py` script to have [this content](https://github.com/quantumblacklabs/kedro/blob/0.17.2/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.ipython/profile_default/startup/00-kedro-init.py).
2. After that, `kedro ipython` and `kedro jupyter notebook` should work out of the box and populate a `session` and `context` variables for you by default. No extra work is required. 
3. You can still manually instantiate a `session` and `context` (option 2 discussed earlier). You will need to make sure that the working directory is the root project directory since you are instantiating a config loader manually.
4. The `session` abstraction shouldn't create any problem with your containerized setup. For all practical intents and purposes, it is just another Python object as the `context`. On this note, could you explain your containerized setup a bit more please? I'm very curious.

The one thing we added in `0.17.2` was requiring a `configure_project(<package_name>)` at the top of the workflow (invoking anything with the Kedro CLI will take care of this bit for you). This step will validate that the `<package_name>` is importable, i.e. the source directory is in the python path. It doesn't seem like this is the case in your environment. However, this should have been a problem in previous Kedro versions as well...

I'm actually happy to jump into a zoom call to help you debug this :) We try our best to not break people's workflows with each update, so if there is anything I can learn from your setup, it will only help us going forward.

**Comment by roumail** [comment]
I will definitely back to you tomorrow and might take you up on the call offer :) have to say that even if I’m able to make it work with kedro 0.17.0, we can’t actually use that version since it has a restrictive pyarrow  version (<1.0) which breaks our code with pandas.parquetdataset (https://github.com/quantumblacklabs/kedro/issues/617). So these are two separate issues we’re trying to resolve amongst the kedro 0.17.x versions.. 

Thanks again for all your support! Really appreciate it.

**Comment by roumail** [comment]
Okay, a quick comment on https://github.com/quantumblacklabs/kedro/issues/727#issuecomment-802144090, I had said Option II isn't working on our actual codebase. We discussed that changing working directory to the project root inside the notebook might help and it did! I also tried the same steps in an `ipython` session and it worked again - of course, the ipython session started from project root didn't require the working directory change. Our main need is to have a way to reliably load the context inside an ipython or jupyter notebook environment, and with your script above, I seem to be able to do that!

![screenshot](https://user-images.githubusercontent.com/32498483/111739299-1f2bf580-8883-11eb-93e3-aec91921cd81.png)

It would be nice to be able to do it using the kedro cli commands, but `%reload_kedro` still gives me an error. I tried `kedro init` too but that didn't seem to help either. 

I'm getting the sense that there are multiple different issues now, some with our test on `kedro new`, some tests on our actual codebase. All of these seem to give different errors. Sometimes the project module isn't found, sometimes it's the templatedconfig error failing at ._start_logging (see https://github.com/quantumblacklabs/kedro/issues/727#issuecomment-801912678)

It might indeed help to schedule a zoom call. Prior to that call, I can follow the steps you listed above to serve as a starting point. Then we can look into other aspects of this problem such as the development environment etc. 

Please let me know what time works for you. My email address is `rohail.taimour@ucb.com`.

Thanks again

**Comment by roumail** [comment]
Another thing we've faced challenges with the new session framework is that we sometimes get errors like this in a notebook/ipython environment

![image](https://user-images.githubusercontent.com/32498483/111748845-51445400-8891-11eb-8068-5a779c00307f.png)

For this working snippet can we replace the line `_activate_session(session)` to something like spark's get or create?

**Comment by limdauto** [comment]
@roumail I sent you an email. Look forward to speaking.

**Comment by roumail** [comment]
```
"""
Workaround for how to load context in a notebook - load_context.py
# https://github.com/quantumblacklabs/kedro/issues/727
"""

from pathlib import Path
from kedro.framework.session import KedroSession
from kedro.framework.startup import _get_project_metadata
from kedro.framework.cli.utils import _add_src_to_path
from kedro.framework.project import configure_project
from kedro.framework.session.session import _activate_session
from kedro.framework.session import get_current_session


def main():
    """
    We assume we are already in the project directory and have launched an ipython session
    For a notebook, we must make sure to cd to project directory
    """
    global context
    global catalog
    project_path = Path.cwd()  # this points to 'notebooks/' folder.
    # check that you're in the project root by presence of pyproject.toml file
    assert (project_path / "pyproject.toml").exists(), "Are you sure your wd is set to the project root" 
    # Get active session if any
    session = get_current_session(silent=True)
    if not session:
        metadata = _get_project_metadata(project_path)
        _add_src_to_path(metadata.source_dir, project_path)
        configure_project(metadata.package_name)    
        session = KedroSession.create(metadata.package_name, project_path)
        _activate_session(session) 
    context = session.load_context()
    catalog = context.catalog


if __name__ == "__main__":
    main()
```

I use this script in a new project by:
```
1. ipython
2. run load_context.py
3. catalog.list()
```

**Comment by limdauto** [comment]
@roumail I found the root cause. If you have a `PYTHONPATH` set, our `_add_src_to_path` doesn't work as expected, i.e. it doesn't add your `src` dir to PYTHONPATH as advertised :D and this breaks kedro ipython && kedro jupyter notebook && reload_kedro.

So if you add a line in the IPython init script's `reload_kedro` function to add the `src` dir to PYTHONPATH manually (don't use our `_add_src_to_path`), it should fix the problem.

We will fix our `_add_src_to_path` going forward as well.

**Comment by sansagara** [comment]
I'm so, so glad the mystery is now solved!!!
We do indeed usually just mark the "src" folder of the project as the "Sources Root" in PyCharm, which automatically adds it to the PYTHONPATH.

**Comment by roumail** [comment]
Thanks alot for investigating @limdauto!

**Comment by dmb23** [comment]
Hi everyone,

Thank you so much for investigating the cause of this issue before I even found the problem! 

But one comment: I started looking into Kedro yesterday to see if I can use it for our workflow, and it took me three hours to find this solution. The bug is still around in 0.17.3. Since it probably does not make sense to update the docs, could the title of this issue maybe be changed into something like "PYTHONPATH breaks `kedro ipython` & `kedro jupyter` to make it easier for people like me to find the solution?

Summary: With 0.17.3 a part of the most basic examples in the docs (i.e. Iris example + `kedro ipython` or `kedro jupyter notebook`) fails when you have set a PYTHONPATH environment variable.

A workaround is to include something like `sys.path.append(str(path / 'src'))` in project_root/.ipython/default_profile/00-kedro-init.py

**Comment by lorenabalan** [comment]
@dmb23 that's a great shout, I've updated the title and now matches more what we have on our backlog. We had to prioritise getting other bug fixes out for 0.17.3 so we couldn't include this fix now, but we'll look at it for the next release! Appreciate everyone's patience with this. 🙏

**Comment by lorenabalan** [comment]
Hi all, apologies that I forgot to update here too, but [a fix](https://github.com/quantumblacklabs/kedro/commit/2a6475ae68882d96d2e5f15247ffe878d3a44683) has been pushed for this and will be out in 0.17.4. Closing this as resolved. 😊
